-- 基估宝移动 PWA：仅用于账号配置、账户账本与交易记录的跨设备同步。
-- 在 Supabase 项目的 SQL Editor 整段执行一次。

create table if not exists public.user_configs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  data jsonb,
  updated_at timestamp with time zone,
  user_id uuid not null unique,
  last_device_id text,
  ytd_return_rate numeric
);

alter table public.user_configs enable row level security;

drop policy if exists "user_configs_select_own" on public.user_configs;
drop policy if exists "user_configs_insert_own" on public.user_configs;
drop policy if exists "user_configs_update_own" on public.user_configs;

create policy "user_configs_select_own" on public.user_configs
  for select using (auth.uid() = user_id);
create policy "user_configs_insert_own" on public.user_configs
  for insert with check (auth.uid() = user_id);
create policy "user_configs_update_own" on public.user_configs
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.update_user_config_full(
  payload jsonb,
  p_last_device_id text default null,
  p_force_takeover boolean default false
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_device_id text;
  v_ytd_rate numeric := null;
begin
  select last_device_id into current_device_id
  from public.user_configs where user_id = auth.uid();

  if current_device_id is not null and p_last_device_id is not null
    and current_device_id != p_last_device_id and not p_force_takeover then
    raise exception 'DEVICE_CONFLICT: Logged in on another device';
  end if;

  if payload ? 'ytdReturnRate' then
    v_ytd_rate := (payload->>'ytdReturnRate')::numeric;
  end if;

  insert into public.user_configs (user_id, data, updated_at, last_device_id, ytd_return_rate)
  values (auth.uid(), payload, now(), p_last_device_id, v_ytd_rate)
  on conflict (user_id) do update set
    data = excluded.data,
    updated_at = excluded.updated_at,
    last_device_id = coalesce(excluded.last_device_id, public.user_configs.last_device_id),
    ytd_return_rate = coalesce(excluded.ytd_return_rate, public.user_configs.ytd_return_rate);
end;
$$;

create or replace function public.update_user_config_partial(
  payload jsonb,
  p_last_device_id text default null,
  p_force_takeover boolean default false
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_device_id text;
  v_ytd_rate numeric := null;
begin
  select last_device_id into current_device_id
  from public.user_configs where user_id = auth.uid();

  if current_device_id is not null and p_last_device_id is not null
    and current_device_id != p_last_device_id and not p_force_takeover then
    raise exception 'DEVICE_CONFLICT: Logged in on another device';
  end if;

  if payload ? 'ytdReturnRate' then
    v_ytd_rate := (payload->>'ytdReturnRate')::numeric;
  end if;

  insert into public.user_configs (user_id, data, updated_at, last_device_id, ytd_return_rate)
  values (auth.uid(), payload, now(), p_last_device_id, v_ytd_rate)
  on conflict (user_id) do update set
    data = coalesce(public.user_configs.data, '{}'::jsonb) || excluded.data,
    updated_at = excluded.updated_at,
    last_device_id = coalesce(excluded.last_device_id, public.user_configs.last_device_id),
    ytd_return_rate = coalesce(excluded.ytd_return_rate, public.user_configs.ytd_return_rate);
end;
$$;

grant execute on function public.update_user_config_full(jsonb, text, boolean) to authenticated;
grant execute on function public.update_user_config_partial(jsonb, text, boolean) to authenticated;
